######################################################################
# Automatically generated by qmake (2.01a) mar. 15. févr. 21:44:44 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
FORMS += src/Maquete.ui
SOURCES += src/maquete.cpp
