######################################################################
# Automatically generated by qmake (2.01a) jeu. 10. févr. 01:17:43 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += Maquete.ui
SOURCES += maquete.cpp
