######################################################################
# Automatically generated by qmake (2.01a) ven. 11. mars 13:30:46 2011
######################################################################


TEMPLATE = app
TARGET = miniunz
DEPENDPATH += .
INCLUDEPATH += . ../includes/zlib/
DESTDIR = ../../workdir/bin

# Input
HEADERS += ioapi.h iowin32.h unzip.h
SOURCES += ioapi.c iowin32.c miniunz.c unzip.c
win32:LIBS += $$(PWD)/../../../Antiplagia/contrib/miniunz/zlib.a
