<<<<<<< HEAD
######################################################################
# Automatically generated by qmake (2.01a) ven. 11. mars 14:07:16 2011
######################################################################
QT += core gui
QT += network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Document.h \
           Google.h \
           ihm.h \
           IhmPopup.h \
           ListTextCicble.h \
           MoteurRecherche.h \
           TextCible.h \
           textdocx.h \
           Yahoo.h \
           Bing.h
FORMS +=   ihm.ui \
           resultat.ui \
           progress.ui
SOURCES += Document.cpp \
           Google.cpp \
           ihm.cpp \
           IhmPopup.cpp \
           ListTextCicble.cpp \
           main.cpp \
           MoteurRecherche.cpp \
           TextCible.cpp \
           textdocx.cpp \
           Yahoo.cpp \
           Bing.cpp
=======
######################################################################
# Automatically generated by qmake (2.01a) ven. 11. mars 14:07:16 2011
######################################################################

QT += core gui
QT += network
QT += webkit
QT += xml

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = ../../workdir/bin/
# Input
HEADERS += Document.h \
           Google.h \
           ihm.h \
           IhmPopup.h \
           ListTextCicble.h \
           MoteurRecherche.h \
           TextCible.h \
           textdocx.h \
    xstring.h
FORMS += ihm.ui
SOURCES += Document.cpp \
           Google.cpp \
           ihm.cpp \
           IhmPopup.cpp \
           ListTextCicble.cpp \
           main.cpp \
           MoteurRecherche.cpp \
           TextCible.cpp \
           textdocx.cpp \
    xstring.cpp
>>>>>>> 184c75a39e5bf0deb9cf857409b212ba6e9095d2
